name: Cargo Build

on:
    push:
    pull_request:

jobs:
    build:
        name: Rust project
        strategy:
            matrix:
                toolchain: [stable, beta, nightly]
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Setup Rust toolchain
              run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

            - name: Run cargo build
              run: cargo build --verbose
